In [6]:
import numpy as np



BASIC ARRAY CREATION

In [4]:
arr=np.array([1,2,3,4])
arr


array([1, 2, 3, 4])

In [3]:
a=[1,2,3.5,"hello"]
a


[1, 2, 3.5, 'hello']

In [7]:
np.array(a)

array(['1', '2', '3', 'hello'], dtype='<U11')

In [4]:
a=[1,2,3.5]
a




[1, 2, 3.5]

In [7]:
np.array(a)

array([1. , 2. , 3.5])

MATRIX



In [8]:
l=[[1,2,3],[4,5,6],[7,8,9]]
np.array(l)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
arr=np.arange(1,11,2)
arr


array([1, 3, 5, 7, 9])

In [13]:
arr=np.zeros((6,8))
arr


array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
arr=np.ones((6,8))
arr


array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [19]:
arr=np.linspace(0,1,100)
arr


array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

RANDOM GENERATION FUNCTIONS

In [20]:
np.random.rand(10)

array([0.55111634, 0.48786217, 0.43523254, 0.31395622, 0.48149923,
       0.16041188, 0.68785431, 0.957522  , 0.80880038, 0.28225116])

In [21]:
np.random.randn(10)

array([-0.16426934,  0.58823165,  1.56563944, -0.44125055, -1.35815879,
        0.00184186, -0.24560229, -0.99308693,  0.60788025,  1.19385175])

In [22]:
np.random.randint(10,20,10)

array([14, 18, 11, 12, 16, 17, 19, 17, 18, 18])

ARRAY ATTRIBUTES

In [26]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
arr.shape

(3, 3)

In [28]:
arr.size

9

In [29]:
arr.dtype

dtype('int32')

ARRAY METHOD

In [30]:
arr.min()



1

In [31]:
arr.max()

9

In [32]:
arr.sum()

45

In [33]:
np.sum(arr,axis = 0)

array([12, 15, 18])

In [34]:
arr.mean()

5.0

In [35]:
arr.std()

2.581988897471611

In [36]:
arr.argmax()

8

In [37]:
arr.argmin()

0

RESHAPING AND RESIZING

In [38]:
arr=np.arange(1,31)
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [39]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

NUMPY INDEXING AND SLICING OF VECTORS

In [1]:
import numpy as np



In [3]:
arr=np.arange(11,21)
arr


array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
arr[0]

11

In [5]:
arr[9]

20

In [7]:
arr[1:5]

array([12, 13, 14, 15])

In [8]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [9]:
arr[3: :2]

array([14, 16, 18, 20])

In [10]:
arr_slice=arr[3: :2]
arr_slice


array([14, 16, 18, 20])

In [11]:
arr[2]

13

NUMPY INDEXING AND SLICING OF MATRIX

In [13]:
arr=np.arange(1,31).reshape(6,5)
arr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [14]:
arr[0]

array([1, 2, 3, 4, 5])

In [15]:
arr[0,0]

1

In [20]:
slice=arr[0:2,2:4]
slice


array([[3, 4],
       [8, 9]])

In [19]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [21]:
arr[3:6,3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])

BOOLEAN INDEXING

In [22]:
arr=np.arange(11,21)
arr


array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [24]:
bool_index=arr%2==0
bool_index


array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [25]:
arr=arr[bool_index]
arr


array([12, 14, 16, 18, 20])

ARRAY OPERATIONS

Arithemetic Operation

In [26]:
a1=np.array([1,2,3,4,5,6])
a2=np.array([7,8,9,10,11,12])

In [27]:
a1+a2

array([ 8, 10, 12, 14, 16, 18])

In [28]:
a1-a2

array([-6, -6, -6, -6, -6, -6])

In [29]:
a1*a2

array([ 7, 16, 27, 40, 55, 72])

In [30]:
a1/a2

array([0.14285714, 0.25      , 0.33333333, 0.4       , 0.45454545,
       0.5       ])

In [31]:
a1//a2

array([0, 0, 0, 0, 0, 0])

In [32]:
a1**a2

array([          1,         256,       19683,     1048576,    48828125,
       -2118184960])

In [33]:
l=[10,20,30,40]
arr=np.array(l)


In [34]:
arr+10

array([20, 30, 40, 50])

In [35]:
arr2=np.arange(1,26).reshape(5,5)
arr2


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [36]:
arr2+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

Deep and Shallow Copy

In [58]:
a=np.arange(1,21)
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [59]:
slice=a[:5]

In [60]:
slice=slice*10
slice


array([10, 20, 30, 40, 50])

In [61]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [62]:
a
b=a.copy()


In [63]:
b[0]=100

In [64]:
b

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [65]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Matrix Operations

In [66]:
A=np.array([[1,2],[3,4]])
B=np.array([[1,2],[3,4]])


In [67]:
A

array([[1, 2],
       [3, 4]])

In [68]:
B

array([[1, 2],
       [3, 4]])

In [70]:
A@B

array([[ 7, 10],
       [15, 22]])

In [72]:
np.dot(A,B)

array([[ 7, 10],
       [15, 22]])

In [73]:
A.T

array([[1, 3],
       [2, 4]])

Stacking Array

In [80]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])


In [81]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [82]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [84]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

Splitting Array

In [86]:
c=np.arange(16).reshape(4,4)
c


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [87]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [93]:
a=np.vsplit(c,2)

In [94]:
for i in a:
     print(i)





[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
